usdigitalresponse/arpa-reporter

- yarn.lock
Rebuild the yarn lockfile.  This should upgrade all dependencies (and transitive dependencies) to the latest versions compatible with the semver declarations in package.json.
> Clean and regenerate lockfile (upgrade everything)

- .eslintrc.js
- .eslintrc.usdr.js
- src/components/FormGroups.vue
- src/server/db/audit-report.js
- src/server/lib/field-name-mapping.js
- src/server/lib/remove-empty-documents.js
- src/server/routes/subrecipients.js
- src/server/services/parse-filename.js
- src/server/services/process-upload.js
- src/server/services/validate-data/certification.js
- src/server/services/validate-data/cover.js
- src/server/services/validate-data/loans.js
- src/server/services/validate-data/subrecipients.js
- src/server/services/validate-data/validate.js
- tests/server/fixtures/add-dummy-data.js
- tests/server/seeds/06_projects.js
- tests/server/services/validate-data/index.spec.js
The last commit in this pull request is the most interesting to review.
I attempted to resolve all of the remaining lint warnings, but decided it made more sense to disable ESLint in a few places, rather than reinvent the application architecture.
> Resolve lint errors!

- .env.example
- src/server/db/audit-report.js
@igor47 I split off that last change you commented on from #74 .
Here I'm also adding the VERBOSE env variable to the .env.example file.  I feel like that could also help future developers discover this configuration?
> Clean up commented-out logger

- README.md
- docker-compose.yml
somewhat simplifies local env setup for this project. this is optional,
you can still use a postgres DB created some other way if desired.
> postgres via docker-compose

- package.json
- src/server/services/generate-arpa-report.js
- yarn.lock
This just lets us keep one fewer dependency around.
> Use XLSX package to stringify CSV file

- src/server/services/parse-filename.js
Our example data already includes the example of a project code including a hyphen `768622-CVR`.
This change switches our filename parsing from splitting file parts on hyphens to matching the entire filename with a regular expression.
> parse-filename: Support project codes with hyphens

- src/server/routes/uploads.js
- src/views/Upload.vue
> /uploads/:id/validate should be a POST request

- src/server/db/period-summaries.js
- src/server/db/reporting-periods.js
- src/server/environment.js
- src/server/lib/audit-report.js
- src/server/lib/log.js
- src/server/lib/subrecipients.js
- src/server/services/get-template.js
- src/server/services/validate-data/validate.js
> Extract common helper functions for `log` and `dir`

- src/server/db/uploads.js
- src/server/routes/uploads.js
- src/server/services/documents.js
- src/server/services/persist-upload.js
- src/server/services/validate-upload.js
I think we want to be able to get all documents for a given period when generating a new export zipfile.  This PR reorganises a few helpers to support that.
> Refactor some document and upload helpers

- src/server/services/generate-arpa-report.js
Addresses some feedback from #269.
---
While we're talking regular expressions, I found this library the other day.
https://github.com/jribbens/verbose-regexp
I believe it's inspired by the verbose-regex feature in python, and it seems like a pretty cool way to get at the power of regular expressions without having to write dense, un-documentable strings of gibberish.
Maybe that's worth trying to incorporate sometime?
> Initialize and execute regex only once

- src/server/services/generate-arpa-report.js
These all came together really smoothly!
> Support EC3 templates in treasury export

- src/server/db/uploads.js
- src/server/routes/reporting-periods.js
- src/views/Uploads.vue
we add a route to pull those from the reporting period. we update the db
query to be consistent with other upload db queries.
fixes #285
> feat: uploads table shows only exported uploads

- src/components/Navigation.vue
- src/views/Login.vue
`viewPeriod` is not available if we're not logged in
> fix: error on logged-out view

- src/server/lib/audit-report.js
- src/server/services/persist-upload.js
- src/server/services/records.js
We probably want to do more with this tab eventually, but mapping between projects and uploads has been highly requested, so we solve that now.
Fixes #340
> Crosswalk between projects and uploads in audit report

- src/server/lib/validation-error.js
- src/server/services/validate-upload.js
- src/views/Upload.vue
fixes #327 
we display mismatch errors as warnings in the UI. we still treat missing fields as fatal errors.
> Validation warnings

- src/server/db/reporting-periods.js
- src/server/routes/exports.js
> fix: consistently use transaction when closing reporting period

- render.yaml
- src/server/environment.js
Use Render's blueprint syntax to declare the servies required to launch a new ARPA instance.
https://render.com/docs/blueprint-spec
> Declare infra with render.com blueprint file

- .env.example
- src/server/environment.js
- src/server/lib/audit-report.js
- src/server/routes/audit-report.js
> Add links to uploads to Audit Report

- src/server/services/validate-upload.js
previously, we only closed it if the upload changed state, leaving db
connections hanging
> fix: ensure validation always closes a transaction

- seeds/02_users.js
Resolution for https://github.com/usdigitalresponse/arpa-reporter/issues/367, adding myself and @mhuang-usdr to the list of admins in the users seed file
> Add new admins to the users seed file

- .eslintrc.js
- src/server/lib/format.js
- src/server/services/generate-arpa-report.js
- tests/unit/server/lib/format.spec.js
> Format multi-select fields to normalize delimiters

- .eslintrc.js
- src/server/lib/format.js
- src/server/services/generate-arpa-report.js
- tests/unit/server/lib/format.spec.js
Release the latest changes to main
> Release 2022-07-09

- src/server/services/generate-arpa-report.js
> Fix typo in "Payments to Individuuals" constant

- src/server/services/validation-rules.js
This is a second attempt at #439!  It looks like I was accidentally overwriting the entire rule with the dropdown list, instead of just the `listvals` field!
> Read project demographics options from dropdowns sheet (attempt 2)

- src/server/services/generate-arpa-report.js
It looks like I overlooked this field name in the June 21st template updates!
Fixes #463
> Update reference to Small_Businesses_Served__c

- src/server/db/reporting-periods.js
- src/server/lib/audit-report.js
- src/server/services/records.js
Collect the latest version of each project in the audit report's project summaries tab.
Fixes #432
> Collect projects from all reporting periods in audit report
