- .github/workflows/ci.yml
- src/components/AgencyHome.vue
- tests/server/mocha_wrapper.sh
- tests/server/reset-db.sh
- tests/server/reset-dbx.sh
This adds a continuous integration workflow that runs linters and tests on pull requests (and on pushes to `main` and `staging`) and reports the results as status checks. It should help make obvious that a PR is not safe before clicking the merge so we don’t have failed deploys or need things like #74 to quickly fix a bad merge.
> Add CI Workflow

- tests/server/lib/subrecipients.spec.js
@Mr0grog I isolated the flakiness to this test suite — which appears to depend on the order in which unit tests are executed.  I think disabling this test until we have a chance to rewrite it makes sense.
> Disable flaky test suite

- vue.config.js
I think we can get hot reloading and Firefox support together after all!
It seems like this line in vue-cli-service is to blame:
https://github.com/vuejs/vue-cli/blob/master/packages/%40vue/cli-service/lib/util/prepareProxy.js#L53
> Fix hot reload firefox

- src/views/ReportingPeriod.vue
Reading through the DocumentForm component it doesn't appear that this type key is used for anything other than labels in the form.  It should be safe to update to a human-friendly name.
Fixes #124
> Fix: Update button should reference "Reporting Period" instead of "ReportingPeriod"

- src/helpers/form-helpers.js
- src/views/ReportingPeriod.vue
For some reason we constrain date inputs to an exact format, MM/DD/YYYY.  We don't specify that anywhere, so it was a bit frustrating for me to use the first time I tried to create a new reporting period.
We're already using moment.js to parse the input value, so I don't see any reason we shouldn't support anything moment can parse.
> Improve date input ergonomics

- .github/dependabot.yml
I merged all open dependabot changes a week ago, but immediately there was a new backlog to resolve.  In addition, several of the new dependencies introduced breaking changes that needed to be resolved by hand.
None of these version updates address meaningful security concerns, so I propose tweaking the dependabot configuration such that it respects the semver declarations in this project's `package.json`.
e.g. After this config change, if we declare a dependency on `"vue": "^2.6.14"`, dependabot will alert us to future minor versions or patches (e.g. `2.7.0` or `2.6.15`), but will not prompt us to upgrade across a major version (`3.2.31`).
My theory is that this will make it much easier for us to merge security patches and bug fixes in a timely fashion.
> Limit Dependabot pull requests to lockfile changes

- .github/dependabot.yml
Keep dependabot notifications and updates focused on user-facing code.
One of the most common "security alerts" identified in development dependencies is "potential denial of service due to slow regular expressions".  We don't want to miss actual user facing security issues because they are drowned in notifications about slow CLI tools.
https://overreacted.io/npm-audit-broken-by-design/
Edit: see an actual example of this alert in our repository [here](https://github.com/usdigitalresponse/arpa-reporter/security/dependabot/6)!
> Dependabot: ignore dev dependencies

- jsconfig.json
This change is completely optional!
Migrating everything to TypeScript is probably more work than it's worth at this point, but I found that I could at least convince VS Code to give me some type hints and feedback in the editor by setting this configuration value in `jsconfig.json`.
The main downside here is that — since you can't actually write type annotations in .js files — you'll see some type errors that cannot be resolved.
> Enable some typechecking features in VS Code

- package.json
Declares vue CLI and eslint dependencies as devDependenices.
This is useful because auditing tools treat these categories differently.
before:
after:
> Move vue/cli and eslint deps to "devDependencies"

- src/server/services/generate-arpa-report.js
- src/server/services/get-template.js
This makes the download workflow _significantly_ faster!  It seems like reading and parsing the template files is the slowest part of this process.
> Cache treasury templates in memory

- package.json
- src/server/services/generate-arpa-report.js
- yarn.lock
[OPTIONAL]
This change uses adm-zip (a js implementation of the zip algorithm) to generate our exported zip file without having to interact with the disk.
I suspected this would meaningfully improve our export times, but I was not able to measure a meaningful performance change.  It's possible that this will change with larger quantities of real data.
The remaining advantages of this approach are:
- we never have to worry about accumulating intermediate export files on disk, and we don't have to think about cleaning those files up
- it fixes two [security](https://github.com/usdigitalresponse/arpa-reporter/security/dependabot/26) [vulnerabilities](https://github.com/usdigitalresponse/arpa-reporter/security/dependabot/27) that dependabot is complaining about.
🤷  I don't think this is as …
> Create exports zip file in-memory

- seeds/04_reporting_periods.js
- tests/server/db/reporting-periods.spec.js
- tests/server/seeds/07_reporting_periods.js
Port the general purpose server seed to the test:server scenario
This is useful, because I've been pointing my local instance at this server_test db, and now I can more easily reset my DB contents.
> Update test:server with ARPA reporting periods

- src/views/Home.vue
Without this fix, the "submit spreadsheet" button on the dashboard does nothing!
> Fix typo: viewingCurrentPeriod -> viewingOpenPeriod

- src/server/services/validate-upload.js
By enabling the `cellDates` flag when parsing spreadsheets, we get JS `Date` objects as values for date fields.  That means we don't need to manually translate from MS date format to utc timestamps anymore.
Fixes #265
> Fix date validation in certification sheet

- src/server/services/generate-arpa-report.js
This completes logic for the following functions:
- generateProject236
- generateProject214
- generateProject2128
- generateProject19
- generateProject18
In addition, I added mapped all EC 1 and EC 2 categories not covered by other templates to the project baseline template.
Addresses #57
> Support exports: all EC 1 and EC 2 subcategories

- src/views/Agencies.vue
- src/views/ReportingPeriods.vue
- src/views/Subrecipients.vue
- src/views/Users.vue
I noticed that we have a different set of styles on each edit button.
This just applies the same set of classes to the edit button in all of our table views.
> Apply the same styles to all table edit buttons

- src/views/NewUpload.vue
The current layout just looks janky to me, so I tried to clean it up.  Apparently bootstrap recommends the `form-control-file` class to avoid this.
https://getbootstrap.com/docs/4.6/components/forms/#form-controls
BEFORE
AFTER
Alternative: #277
> Use bootstrap's recommended form-control-file class

- src/server/services/generate-arpa-report.js
It might be slightly easier to land #302 first, then this, to avoid merge conflicts.
> Support EC7 templates in treasury export

- src/components/DownloadButton.vue
- src/components/DownloadTemplateBtn.vue
- src/views/Home.vue
I rewrote this on top of the latest UI changes, and in a way that hopefully supports all download buttons!
> Display a loading spinner while waiting for treasury export! (v2)

- .eslintrc.js
- jsconfig.json
- package.json
- src/server/routes/application_settings.js
- src/server/services/validate-upload.js
- tsconfig.json
- yarn.lock
As discussed in Slack, forgetting to `await` a Promise is a frequent pain point. This adds a TypeScript-based lint rule that picks this up and gives you errors like this:
```
/Users/mattb/Desktop/usdr/arpa-reporter/src/server/lib/audit-report.js
590:5  error  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
/Users/mattb/Desktop/usdr/arpa-reporter/src/server/lib/subrecipients.js
44:9  error  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises …
```
> Add tsconfig and @typescript-eslint/no-floating-promises lint rule

- migrations/20220616180456_overhaul_reporting_periods.js
- seeds/04_reporting_periods.js
- src/server/access-helpers.js
- src/server/db/reporting-periods.js
- src/server/db/settings.js
- src/server/environment.js
- src/server/routes/reporting-periods.js
- src/server/services/get-template.js
- src/store/index.js
- src/views/NewTemplate.vue
- src/views/ReportingPeriod.vue
- src/views/ReportingPeriods.vue
- tests/server/db/settings.spec.js
- tests/server/seeds/07_reporting_periods.js
We do a few things here:
* Remove the oodles of unused columns on the `reporting_periods` table
* Make the `certified_by` a FK reference to users
* Change the way custom period templates are stored (which fixes #309 )
* Moves remaining single-purpose API interactions into relevant components (for uploading a template and certifying a reporting period)
* fix faulty logic around certification, which should fix the comment we heard this afternoon re "I always have to ask Larry to certify the period for me"
> Refactor reporting period management

- src/server/db/reporting-periods.js
- src/server/lib/audit-report.js
- src/server/routes/exports.js
- src/server/routes/reporting-periods.js
- src/server/routes/uploads.js
- src/server/services/get-template.js
- src/server/services/persist-upload.js
- src/server/services/validate-upload.js
- tests/server/db/reporting-periods.spec.js
This is a follow-up for the following comment:
https://github.com/usdigitalresponse/arpa-reporter/pull/317#discussion_r897073256
> Refactor: db/reporting-periods exports verbose names

- migrations/20220627001634_remove_validation_messages.js
- migrations/20220627001742_key_uploads_with_uuid.js
- src/helpers/short-uuid.js
- src/server/routes/uploads.js
- src/server/services/persist-upload.js
- src/views/Upload.vue
- src/views/Uploads.vue
First, this change is totally optional!  I don't think it's that bad if we never expunge auto-incrementing IDs from the ARPA reporter.
However, if we are interested in moving toward UUID (or other string-like) keys, I think uploads is probably the most valuable table to migrate now.  This is because once we have real reporting cycles underway, upload IDs will exist in quite a few places.
Upload IDs as foreign keys can be migrated, but upload IDs will also end up in upload files persisted on disk as well as in upload links in audit reports.  Resolving _all_ discrepancies after-the-fact may never be completely possible.
---
If we do tackle this change now, we should have one less set of ID conflicts to deal with whenever we merge RI, CT and OH instances.  👍 
@igor47 if you do manage to take …
> Change the `uploads` table primary key to a UUID

- src/server/services/validate-upload.js
Fixes the exception error message that is returned when the validation code tries to call `.split()` on an empty ec-code cell value. It checks for the empty value and returns a human-readable validation error before the exception can be thrown.
> Give human-readable validation when missing EC code

- README.md
- RENDER.md
We should remove this file when merging ARPA and GOST repositories.
> Document deployment process with RENDER.md

- src/server/services/generate-arpa-report.js
To test this, I downloaded Joe's latest test template (10003d) from Google Drive.
- Upload this test timplate into local tool
- Download treasury export
- Log into treasury portal (details in 1password)
- Open "P&E - Mindy H. UAT Testing" profile
- Select Projects tab
- Create new project
- Select EC 1 & 1.12
- Click bulk upload link
- Upload the generated projectBaselineBulkUploadTemplate.csv file
- It should validate correctly!
> Output line endings as required by Treasury portal

- src/server/services/generate-arpa-report.js
Without this setting, some of the line breaks in the project bulk upload templates become ambiguous.
Without `forceQuotes`:
With `forceQuotes`:
> Re-enable "forceQuotes" for treasury export

- src/server/lib/format.js
- src/server/services/generate-arpa-report.js
- tests/unit/server/lib/format.spec.js
Rewrite all "detailed expenditure category" strings before printing to treasury output.
This ensures that regardless of input template used, we always output the current value expected by treasury.
> Format subcategories in treasury export

- src/server/services/generate-arpa-report.js
Fix for https://github.com/usdigitalresponse/arpa-reporter/issues/434
The obligation field was incorrectly specified twice in a row, instead of giving the obligation and then the expenditures
> Fix Issue #434: Correct typo where Obligation was incorrectly used twice

- src/server/lib/format.js
Fix for https://github.com/usdigitalresponse/arpa-reporter/issues/435
Updates the category name provided in the output formatter to the new version as specified in the issue.
I also checked the current bulk upload templates to see if the other categories have changed (they have not).
> Fix #435: Update EC7 name to new shorter form

- src/server/services/validate-upload.js
@trumanc I decided to split this off as a distinct PR so we can discuss the right approach separately.
I think it's probably less confusing to agency users to not indicate a warning at all as long as the numeric code matches a known subcategory.  How does that sound?
> Don't bother validating description of EC codes

- src/server/services/validation-rules.js
Reverts usdigitalresponse/arpa-reporter#439
This merge has caused errors on staging. I was able to repro the bug locally, and then fix it by reverting this change. Here's the error message from the logs on staging:
> Revert "Read project demographics options from dropdowns sheet"

- scripts/generateRules.mjs
- src/server/lib/templateRules.json
- src/server/services/validation-rules.js
The `generateRules` script was still pulling dropdown value lists from the hidden row within each tab that had inconsistent/incorrect values in many cases. 
We had identified and corrected some of those mistakes manually in `validation-rules.json`, but hadn't addresses the issue systematically so we were regularly getting more errors reported. 
This PR changes the system to ignore those often-incorrect lists, and instead uses the lists recorded in the Dropdowns tab of the worksheet to populate the extracted rules. The change resulted in around 370 lines of corrected validations.
It requires manually recording which field-ids map to which dropdown names, so I've added that mapping to the script, and included an error check so that when the Dropdowns tab is updated in the future it will …
> Extract dropdown values from correct tab

- src/server/lib/format.js
- src/server/services/generate-arpa-report.js
- tests/unit/server/lib/format.spec.js
This just removes hyphens from the EIN/TIN field.  (I don't know what the difference between an EIN and TIN is. 🤷)
Fixes #462
> Format TIN in treasury exports

- src/server/services/records.js
In one RI upload, there are some fields filled out in the EC 2 sheet, even though EC 1 was later selected.
https://ri-arpa-reporter-web.onrender.com/uploads/7566acc4-3485-4ecb-a846-7cf5f39f97fd
The EC 2 sheet is hidden, but we still read it when extracting records from the upload.  This change explicitly ignores hidden sheets, to prevent this from happening in the future.
Fixes #453
> Ignore hidden sheets when extracting records from uploads

- src/server/services/generate-arpa-report.js
Noticed a filename was incorrect, and verified that it caused errors when trying to export data of those project types. After correction the export worked correctly.
> Correct template filename typo

- scripts/generateRules.mjs
- src/server/services/generate-arpa-report.js
- src/server/services/records.js
- src/server/services/validate-upload.js
- src/server/services/validation-rules.js
Adds two new systems:
1) a new system for doing value formatting. These validations are more powerful (and dangerous) than the previous formatting, because they will also affect the values that are printed to exports.
2) A structured system for recording problems we've detected with dropdown values. It lets us easily refer to a specific value in the worksheet, and provide information about what that value should be corrected to, and what other values we should allow. This system uses the new formatting system to coerce any allowable values into the correct one.
(also fixes a bug I found where 1.9 projects were not exporting the cancellation reason)
Here are some output csvs, shown pre-fix and post-fix to show how the output dropdown values were fixed. Both cases used the same input …
> Add persistentFormatters and dropdown corrections

- scripts/generateRules.mjs
- src/server/services/generate-arpa-report.js
- src/server/services/records.js
- src/server/services/validate-upload.js
- src/server/services/validation-rules.js
- yarn.lock
This release included fixes for:
- Incorrect dropdown values: 
If the uploaded worksheet included any of the following incorrect values
- Affordable housing supportive housing or recovery housing
- COVID-19 testing sites and laboratories and acquisition of related equipment
- Family or childcare
Then the validation will still pass, and the export csvs will include these corrected values instead:
- Affordable housing, supportive housing, or recovery housing
- COVID-19 testing sites and laboratories, and acquisition of related equipment
- Family or child care
Unfortunately we still don't know what the correct value for "Mitigation measures in small businesses, nonprofits and impacted industries" is supposed to be, so we haven't fixed that. 
- Fixed a bug that caused exports for EC codes 1.9 …
> Release 2022-07-27

- src/server/services/records.js
Add a memoization layer to upload reads.  This ensures that the same upload is not read from disk more than once within a single request.
The audit report generation process could end up reading the same upload from disk two or more times.  Rather than try to complicate the logic for report generation, this change caches audit report reads.
To avoid leaking memory, this cache is only preserved on the express request object.  This allows the node process to garbage collect cached uploads after the request has resolved.  This will be very important in a multi-tenant deployment.
> Memoize filesystem reads for uploads (within request)

- tests/unit/server/lib/format.spec.js
Test was broken on `staging` branch, caused by 3ec63f4ceb6
> Fix format.spec.js test broken by 3ec63f4ceb6

- src/components/Navigation.vue
- src/server/access-helpers.js
- src/server/db/users.js
- src/server/routes/sessions.js
- src/server/routes/users.js
- src/views/Agency.vue
- src/views/Home.vue
- src/views/User.vue
- src/views/Users.vue
For the tables that will be shared with GOST, this makes several changes in advance on the ARPA side to make its usage similar to in GOST and only depending on fields that are present in GOST's accessors. Notably:
- `users`:
- instead of having `role` be a string field on user objects, it is not an object with the `roles` row's fields (one place we do not do this is in the add/edit user flow because StandardForm would have to be changed significantly; instead we just convert back and forth between the two formats on the client)
- don't include `agency_name` and `agency_code` fields on user objects; instead load that information separately from the VueX store in the one clientside place that cared about them
- require an `agency_id` when creating or updating a user, since it is intended to …
> GOST integration: Adjust database accesses for shared tables

- src/server/lib/audit-report.js
- src/server/services/records.js
Quick update that should help with audit report slowness as reported in https://github.com/usdigitalresponse/arpa-reporter/issues/487 by changing some O(N) object-creation operations to O(1) object-update operations.
The splat operator is causing us the code to create a new object everytime, instead of just making small modifications to the object in place.
This is particularly troublesome in records.js, where the object has an entry for every single project for this tenant, and we are looping over every historical submission/version of each record.
> Collate report data more efficiently

- src/components/Navigation.vue
- src/router/index.js
- src/server/configure.js
- src/server/index.js
- src/views/ReportingPeriods.vue
- tests/server/fixtures/add-dummy-data.js
- tests/server/routes/route_test_helpers.js
- tests/unit/components/Navigation.spec.js
- Remove some bad syntax that Babel (in my [import rewriter](https://github.com/usdigitalresponse/usdr-gost/pull/297) script) choked on
- add an environment variable check to gate VueRouter `base` on whether running in standalone ARPA reporter repo or GOST
- fix dependencies on being mounted at root path
- remove raw reference to document.location in Navigation.vue; use VueRouter's `$route` object instead which accounts for varying `base`
- replace some `a` tags with `router-link` tags
- organize `configure.js` into separate functions that can be more easily called from GOST's after repo merge
> GOST integration: misc preparations for copy

- src/server/db/users.js
This fixes one callsite missed in #505's rework of how user objects are dealt with: when creating a new user in legacy ARPA Reporter environment, need to convert `user.role` object back into string (in GOST, this code is replaced).
> Followup fix from #505: handle role properly when creating new users

- scripts/generateRules.mjs
- src/server/environment.js
- tests/server/environment.spec.js
- tests/server/fixtures/add-dummy-data.js
- tests/server/helpers/is_gost.js
- tests/server/mocha_init.js
- tests/server/mocha_wrapper.sh
- tests/server/reset-db.sh
- tests/server/seeds/00_gost_tenants.js
- tests/server/seeds/01_roles.js
- tests/server/seeds/02_users.js
Sister PR to https://github.com/usdigitalresponse/usdr-gost/pull/310, this makes ARPA-side changes to allow ARPA tests to run in the GOST repo.
Namely:
- `SRC_DIR` is refactored into `SERVER_CODE_DIR` to remove dependency on a specific directory structure
- its test is updated accordingly, as well as removing dynamic require which my import rewriter script cannot handle. I don't really see a strong reason it was like this before? Perhaps @ajhyndman or @igor47 have an idea?
- Add a seed for GOST's `tenants` table (no-ops in legacy ARPA repo)
- Modify `add-dummy-data` script to conditionally populate required `agencies.main_agency_id` column when running in GOST repo
- Modify test seeds for `roles` and `users` to support the GOST versions of those tables
- Adjust the regexes used in …
> GOST integration: ARPA-side changes to allow running ARPA tests in GOST repo

- src/router/index.js
- src/views/Login.vue
We set a new URL param, `redirect_to` when redirecting to the login page from another VueRouter route, and the login page forwards that to its `/api/sessions` call.
In standalone ARPA Reporter repo, this parameter is ignored. But in GOST once https://github.com/usdigitalresponse/usdr-gost/pull/288 is merged, it will cause the login link email that's sent to also include a `redirect_to` field. In this way, after logging in using the GOST `/api/sessions` endpoints, the user is redirected back to ARPA Reporter rather than going to the GOST/ID Tool dashboard.
The VueRouter APIs used here automatically account for the `base` config option that will be set in GOST to nest the ARPA Reporter app under a URL path.
> GOST Integration: populate redirect_to field during login

- package.json
- scripts/dump_data.js
- src/server/routes/reporting-periods.js
- src/server/services/get-template.js
- src/server/services/persist-upload.js
- yarn.lock
This is one part of what will be used to migrate existing partners with their own Render instances to a unified ARPA-Reporter-in-GOST world. The idea is that you'd:
1. run this script on their ARPA instance
2. temporarily enable SSH on both the ARPA instance and GOST prod instance
3. scp/rsync the file from ARPA to GOST
4. disable SSH
5. run a corresponding import script on the GOST side (implemented in https://github.com/usdigitalresponse/usdr-gost/pull/312)
6. delete the zip files on both sides
One concern about this script is that `adm-zip` reads the contents of all uploaded files into memory before writing the output zip. I'm not sure how many/how big uploads are practically dealing with, though I'm guessing this probably won't be a big issue?
There is also one minor drive-by fix in …
> GOST integration: script to dump all relevant database tables and all uploaded files to a zip

- src/server/use-request.js
This is referenced in a DB shim (see [here](https://gist.github.com/mattbroussard/7f725a9090ee5a9ff9be77eaab555e76)), but was not actually exported.
> Bugbash fix: export useUser

- src/views/Upload.vue
Updates the upload screen to use the reporting period name instead of the id in the. two places it is dipslayed. This will become a bigger concern as we lean in to multi-tenancy in the GOST repo and period ids will be significantly higher than they currently are.
Old screenshot (says "period 1" in the rows of the left column, and the title of the right column)
Replaced both instances in this updated screenshot
> Display reporting period name, not id
